# Generated by Django 3.2.2 on 2022-11-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taxesModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('muni', 'Impuestos Municipales'), ('prov', 'Impuestos Provinciales'), ('naci', 'Impuestos Nacionales'), ('sepu', 'Servicios Publicos'), ('sepr', 'Servicios Privados')], max_length=4, null=True)),
                ('tax', models.CharField(blank=True, max_length=100, null=True)),
                ('money', models.FloatField(blank=True, null=True)),
                ('pay_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
    ]
